#!/bin/env bash

# Adapt from get_vsixpkg() of the original update_install_exts.sh

set -eu -o pipefail

# Helper to just fail with a message and non-zero exit code.
function fail() {
    echo "$1" >&2
    exit 1
}

function escape_doublequotes {
    echo "$1" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g'
}

PUBLISHER=""
NAME=""
VER=""
NO_HASH=false
NO_META=false

declare -a NONFLAG_ARGS=()

if [[ "$#" -eq 0 ]]; then
fail "Expect PUBLISHER and NAME"
fi

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -h|--help)
            cat <<END_HELP
Usage: nix-prefetch-vscode-marketplace [OPTIONS] PUBLISHER NAME VERSION=latest

Fetch the vscode extension from the official marketplace
and print the registryRef (previously \"mktplcRef\") attributes in JSON format

Options:
  -h, --help                Print this help and exit.
  -H, --no-hash             Do not print the nix-hash value of this extension.
                            Since the current way to get the extension version
                            from the vscode marketplace
                            is to download and extract the VSIX file
                            this will not save the fetching time
                            as it does for the Open VSX Registry
  -M, --no-meta             Do not print the meta parameters of this extension.
                            This will not save the fetching and extracting time
                            since extension version is also inside package.json
  -t, --tmpdir TMPDIR       Specify the directory
                            to create temporary directories in.
                            Default to \`"\${TMPDIR:-/tmp}"\` by \`mktemp\`
                            from the environment.

If non-flag arguments (PUBLISHER, NAME, VERSION, etc.) happen to start with '-',
they should be escaped with a '\\' prefix.

END_HELP

            exit 0
            ;;
        -H|--no-hash)
            NO_HASH=true
            shift 1
            ;;
        -M|--no-meta)
            NO_META=true
            shift 1
            ;;
        -t|--tmpdir)
            if [[ "$#" -lt 2 ]]; then
                fail "Expect $1 TMPDIR"
            fi
            export TMPDIR="$2"
            shift 2
            ;;
        -)
            fail "Unexpected argument $1"
            ;;
        -?*)
            fail "Unexpected argument $1"
            ;;
        \\-*)
            # If an argument begins with '\-'
            # Get the second and the following characters
            # and put into NONFLAG_ARGS
            NONFLAG_ARGS+=("${1:1}")
            shift 1
            ;;
        *)
            NONFLAG_ARGS+=("$1")
            shift 1
            ;;
    esac
done

if [[ "${#NONFLAG_ARGS[@]}" -lt 2 ]]; then
    fail "Expect PUBLISHER and NAME"
fi
PUBLISHER="${NONFLAG_ARGS[0]}"
NAME="${NONFLAG_ARGS[1]}"
if [[ "${#NONFLAG_ARGS[@]}" -lt 3 ]] || [[ -z "${NONFLAG_ARGS[2]}" ]]; then
    VER="latest"
else
    VER="${NONFLAG_ARGS[2]}"
fi


N="$PUBLISHER.$NAME"

# Create a tempdir for the extension download.
EXTTMP=$(mktemp -d -t vscode_exts_XXXXXXXX)

# Clean up the temp folder whenever exit
function clean_up {
    rm -rf "$EXTTMP"
}

trap clean_up EXIT

URL="https://$PUBLISHER.gallery.vsassets.io/_apis/public/gallery/publisher/$PUBLISHER/extension/$NAME/$VER/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"

# Quietly but delicately curl down the file, blowing up at the first sign of trouble.
curl --silent --show-error --fail -o "$EXTTMP/$N.zip" "$URL"
# Unpack package.json from the VSIX file
unzip -qp "$EXTTMP/$N.zip" "extension/package.json" > "$EXTTMP/package.json"
# Get the version from package.json
VER_FETCHED="$(jq -r '.version' "$EXTTMP/package.json")"
DESCRIPTION=""
HOMEPAGE=""
LICENSE_RAW=""
if ! $NO_META; then
    DESCRIPTION="$(jq -r '.description' "$EXTTMP/package.json")"
    HOMEPAGE="$(jq -r '.homepage' "$EXTTMP/package.json")"
    LICENSE_RAW="$(jq -r '.license' "$EXTTMP/package.json")"
fi
if [[ "$VER" = "latest" ]]; then
    VER="$VER_FETCHED"
else
    if [[ "$VER" != "$VER_FETCHED" ]]; then
    fail "Fetched version ($VER_FETCHED) does not match the specified version ($VER)"
    fi
fi

SHA=""
# Calculate the SHA256
if ! $NO_HASH; then
    SHA="$(nix-hash --flat --base32 --type sha256 "$EXTTMP/$N.zip")"
fi

cat <<EOF
{
  "name": "$(escape_doublequotes "$NAME")"
, "publisher": "$(escape_doublequotes "$PUBLISHER")"
, "version": "$(escape_doublequotes "$VER")"
EOF
if ! $NO_HASH; then
    cat <<END_OF_HASH
, "sha256": "$SHA"
END_OF_HASH
fi
if ! $NO_META; then
    if [[ -n "$DESCRIPTION"  ]] && [[ "$DESCRIPTION" != "null" ]]; then
        echo ", \"description\": \"$(escape_doublequotes "$DESCRIPTION")\""
    fi
    if [[ -n "$HOMEPAGE"  ]] && [[ "$HOMEPAGE" != "null" ]]; then
        echo ", \"homepage\": \"$(escape_doublequotes "$HOMEPAGE")\""
    fi
    if [[ -n "$LICENSE_RAW"  ]] && [[ "$LICENSE_RAW" != "null" ]]; then
        echo ", \"license-raw\": \"$(escape_doublequotes "$LICENSE_RAW")\""
    fi
fi
cat <<EOF
}
EOF
